In [1]:
import torch

In [2]:
torch.__version__

'2.5.1+cpu'

In [5]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
    pass

In [7]:
a = torch.empty(2,3) # fill the random value taking a garbage value coming from RAM.

In [8]:
a

tensor([[7.8930e-31, 7.4409e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [9]:
type(a)

torch.Tensor

In [10]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
torch.rand(3,4)

tensor([[0.0214, 0.3426, 0.6418, 0.7819],
        [0.8211, 0.9797, 0.4988, 0.4184],
        [0.1115, 0.7132, 0.5613, 0.9314]])

In [14]:
torch.rand(3,4)

tensor([[0.5952, 0.1276, 0.7977, 0.6640],
        [0.4018, 0.6459, 0.7190, 0.2708],
        [0.0926, 0.1274, 0.6311, 0.0690]])

In [16]:
torch.rand(3,4)

tensor([[0.7041, 0.5573, 0.6959, 0.9849],
        [0.2924, 0.4823, 0.6150, 0.4967],
        [0.4521, 0.0575, 0.0687, 0.0501]])

In [17]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [19]:
b = torch.tensor([[1,2,3], [4,5,6]])

In [20]:
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [33]:
torch.empty_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [30]:
torch.empty_like(b)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [29]:
b.shape

torch.Size([2, 3])

In [21]:
b.ndim

2

In [22]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
torch.arange(0,9) # exclude the last value

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [25]:
torch.linspace(0,10,20) # Used for to create the random weight with centrain range.

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [27]:
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [28]:
torch.full((3,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [37]:
torch.rand_like(b, dtype=torch.float16)

tensor([[0.9302, 0.9971, 0.5039],
        [0.5356, 0.1250, 0.2393]], dtype=torch.float16)

In [38]:
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [39]:
b + 2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [40]:
b - 2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [41]:
b * 3

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [42]:
b / 2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [43]:
b // 2

tensor([[0, 1, 1],
        [2, 2, 3]])

In [44]:
c = torch.tensor([1, -2, 3, -4])

In [45]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [46]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [47]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [48]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [49]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [50]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [52]:
torch.randint(size=(3,4), low=0, high=10)

tensor([[6, 2, 8, 9],
        [2, 0, 9, 9],
        [4, 4, 9, 4]])

In [53]:
torch.randint(size=(3,4), low=0, high=10, dtype=torch.float32)

tensor([[4., 5., 4., 0.],
        [8., 9., 3., 0.],
        [9., 3., 7., 9.]])

In [56]:
e =torch.randint(size=(3,4), low=0, high=10, dtype=torch.float32)

In [55]:
torch.sum(c)

tensor(-2)

In [57]:
torch.sum(e, dim=1)

tensor([22., 25., 25.])

In [58]:
torch.sum(e, dim=0)

tensor([17., 13., 18., 24.])

In [59]:
torch.mean(e, dim=0)

tensor([5.6667, 4.3333, 6.0000, 8.0000])

In [60]:
torch.min(e)

tensor(1.)

In [61]:
torch.max(e)

tensor(9.)

In [64]:
e

tensor([[5., 2., 9., 6.],
        [6., 2., 8., 9.],
        [6., 9., 1., 9.]])

argmin it is giving mea index of highest value in matrix

In [62]:
torch.argmax(e)

tensor(2)

argmin it is giving mea index of minimum value in matrix

In [63]:
torch.argmin(e)

tensor(10)

In [85]:
f =torch.randint(size=(3,2), low=0, high=10)
g =torch.randint(size=(2,3), low=0, high=10)

In [86]:
f

tensor([[6, 9],
        [5, 0],
        [4, 0]])

In [87]:
g 

tensor([[3, 7, 9],
        [6, 6, 2]])

In [88]:
torch.matmul(f,g)

tensor([[72, 96, 72],
        [15, 35, 45],
        [12, 28, 36]])

In [1]:
def dy_dx(x):
    return 2*x

In [2]:
dy_dx(4)

8

In [3]:
import torch
x = torch.tensor(3.0, requires_grad=True)

In [4]:
x

tensor(3., requires_grad=True)

In [5]:
y=x**2 # forward propagation

In [6]:
y

tensor(9., grad_fn=<PowBackward0>)

In [7]:
y.backward()

In [8]:
x.grad

tensor(6.)

In [11]:
import math

In [12]:
def dz_dx(x):
    return 2*x*math.cos(x**2)

In [13]:
dz_dx(3)

-5.466781571308061

In [14]:
x=torch.tensor(3.0,requires_grad=True)

In [15]:
x

tensor(3., requires_grad=True)

In [17]:
y=x**2
z=torch.sin(y)

In [18]:
y

tensor(9., grad_fn=<PowBackward0>)

In [19]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [20]:
z.backward()

In [21]:
x.grad

tensor(-5.4668)

pytorch autograd docs <a href="https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html">here</a>

In [22]:
import torch.nn as nn

### <font color="green">Basic Neural Network</font>

In [43]:
class Model(nn.Module):

    def __init__(self, new_features):
        super().__init__()
        self.linear=nn.Linear(new_features, 1)
        self.sigmoid=nn.Sigmoid()
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out


In [44]:
data = torch.rand(10,5)

In [45]:
data

tensor([[0.6896, 0.7911, 0.5316, 0.8928, 0.4350],
        [0.4897, 0.1139, 0.1763, 0.9983, 0.4150],
        [0.1609, 0.5760, 0.7517, 0.1983, 0.0304],
        [0.7236, 0.6543, 0.6577, 0.0440, 0.6792],
        [0.7613, 0.9515, 0.9234, 0.0170, 0.9918],
        [0.5966, 0.8292, 0.7256, 0.2584, 0.1196],
        [0.6888, 0.0867, 0.3594, 0.4364, 0.0850],
        [0.6827, 0.7822, 0.2850, 0.5410, 0.5137],
        [0.8775, 0.6690, 0.2560, 0.4462, 0.5389],
        [0.1806, 0.3465, 0.9868, 0.8479, 0.6568]])

In [46]:
data.shape

torch.Size([10, 5])

In [47]:
model=Model(data.shape[1])

In [48]:
model(data)

tensor([[0.5210],
        [0.4907],
        [0.5341],
        [0.5870],
        [0.5847],
        [0.5715],
        [0.5629],
        [0.5523],
        [0.5772],
        [0.4583]], grad_fn=<SigmoidBackward0>)

In [52]:
model.linear.weight

Parameter containing:
tensor([[ 0.3840,  0.0474, -0.0622, -0.3448, -0.0984]], requires_grad=True)

In [53]:
model.linear.bias

Parameter containing:
tensor([0.1655], requires_grad=True)

In [49]:
data.shape[0] #Row

10

In [51]:
data.shape[1] #Col

5

In [54]:
class Model(nn.Module):
    
    def __init__(self, new_features):
        super().__init__()
        self.linear1=nn.Linear(new_features, 3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [55]:
data1=torch.rand(10,5)

In [56]:
data1

tensor([[0.6652, 0.2834, 0.7275, 0.5874, 0.9270],
        [0.5893, 0.3387, 0.8596, 0.9179, 0.0735],
        [0.4247, 0.7686, 0.4153, 0.5592, 0.4248],
        [0.8028, 0.4109, 0.5397, 0.5166, 0.6717],
        [0.1722, 0.7970, 0.3456, 0.8061, 0.2584],
        [0.5247, 0.7385, 0.0793, 0.6229, 0.3931],
        [0.8822, 0.7098, 0.1081, 0.5980, 0.8374],
        [0.9524, 0.4352, 0.9976, 0.9286, 0.6192],
        [0.7842, 0.6784, 0.8153, 0.7408, 0.9820],
        [0.9503, 0.8308, 0.3178, 0.0532, 0.2193]])

In [58]:
data1.shape

torch.Size([10, 5])

In [57]:
model=Model(data1.shape[1])

In [59]:
model(data1)

tensor([[0.4378],
        [0.4360],
        [0.4360],
        [0.4360],
        [0.4360],
        [0.4360],
        [0.4360],
        [0.4360],
        [0.4360],
        [0.4360]], grad_fn=<SigmoidBackward0>)

In [60]:
model.linear1.weight

Parameter containing:
tensor([[-0.2212, -0.4241, -0.0134, -0.2813,  0.2800],
        [-0.1878, -0.2316,  0.0040, -0.4352, -0.1755],
        [-0.1323,  0.1717, -0.0838,  0.0370,  0.0915]], requires_grad=True)

In [61]:
model.linear1.bias

Parameter containing:
tensor([ 0.2359, -0.0320, -0.3901], requires_grad=True)

In [62]:
model.linear2.weight

Parameter containing:
tensor([[ 0.1354,  0.1060, -0.1565]], requires_grad=True)

In [63]:
model.linear2.bias

Parameter containing:
tensor([-0.2575], requires_grad=True)

In [64]:
from torchinfo import summary

In [65]:
summary(model, input=(10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

In [ ]:
import torch
import torch.nn as nn

class Model()

In [66]:
import pandas as pd

In [68]:
data=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [69]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [70]:
data.shape

(569, 33)

In [71]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [73]:
df =data.drop(columns=['id', 'Unnamed: 32'])

In [74]:
df.head(3)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38           122.8     1001.0   
1         M        20.57         17.77           132.9     1326.0   
2         M        19.69         21.25           130.0     1203.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33            184.6   
1         0.1812  ...         24.99          23.41            158.8   
2         0.2069  ...         23.57          25.53            152.5   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  

[3 rows x 31 columns]

Benign = No cancer

malignant = cancer

In [75]:
df["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

https://github.com/sunnysavita10/genai_bootcamp/blob/main/pytorch.ipynb